# Site settings
title: SpindelNet | IT konsulent
email: webmaster@spindelnet.dk
description: "SpindelNet"
baseurl: ""
url: "https://www.spindelnet.dk"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

gems:
  - jekyll-sitemap
